# Generated by Django 4.1.3 on 2023-06-25 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='cliente_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_enviados', to='logistics.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='transportista_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_asignados', to='logistics.transportista'),
            preserve_default=False,
        ),
    ]
