# Generated by Django 4.1.3 on 2023-06-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_paquete_cliente_id_paquete_transportista_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paquete',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='paquete',
            old_name='transportista_id',
            new_name='transportista',
        ),
    ]
